config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  root 'pages#home'
  get :search, to: 'products#search'
  get :my_favorite, to: 'products#my_favorite'

  resources :orders do
    collection do
      post :return
    end
  end

  resources :shops do
    resources :products, shallow: true do
      member do
        post :favorite
      end
    end
  end

  resources :order_list, shallow: true

  resources :users do
    collection do
      post :add_coupon
      get :change_coupon_status
    end
  end

  resources :coupons do
    collection do
      get :list
    end
  end

  resources :rooms do
    resources :messages , shallow: true
  end

  resource :carts, only:[:show, :destroy] do
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    get :checkout
    post :return
    get 'get_coupon_info/:id', action: 'get_coupon_info', as: 'get_coupon_info'
    get 'cal_totalprice', action: 'cal_totalprice', as: 'cal_totalprice'
    delete :empty
    delete 'destroy/:id', action: 'destroy', as: 'destroy'
    put 'update_item/:id', action: 'update_item', as: 'update_item'
  end
end

app/models/shop.rb
# frozen_string_literal: true

class Shop < ApplicationRecord
  belongs_to :user
  has_many :products
  has_many :coupons
  has_many :shop_orders
  has_many :orders, through: :shop_orders
  validates :name, presence: true
  validates :tel, presence: true
end

app/controllers/shops_controller.rb
# frozen_string_literal: true

class ShopsController < ApplicationController
  layout "store"

  def index
    # @products = Product.where(shops: current_user.shop)
    @products = current_user.shop.products
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = current_user.build_shop(shop_params)
    if @shop.save
      redirect_to shops_path
    else
      render :new
    end
  end

  def edit
    @shop = current_user.shop
  end

  def update
    @shop = current_user.shop
    if @shop.update(shop_params)
      redirect_to shops_path
    else
      render :edit
    end
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :tel)
  end
end

app/helpers/shops_helper.rb
# frozen_string_literal: true

module ShopsHelper

  def coupon_TimeWithZone_convert(timewithzone)
    timewithzone.strftime('%Y/%m/%d')
  end
end

app/views/shops/edit.html.erb
<div class="overflow-hidden sm:rounded-sm my-20 m-auto mt-40">
  <div class="border-t border-gray-200 rounded-sm">
      <%= form_for @shop do |f| %>

        <div class="bg-white py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <div class="block text-sm font-medium text-gray-700">
            <%= f.label :name, '賣場名稱' %>
          </div>
          <div class="mt-1 text-sm text-gray-900 border-b border-text-200 sm:mt-0 sm:col-span-2">
            <%= f.text_field :name %>
          </div>
        </div>

        <div class="bg-white py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <div class="block text-sm font-medium text-gray-700">
            <%= f.label :tel, '聯絡電話' %>
          </div>
          <div class="mt-1 text-sm text-gray-900 border-b border-text-200  sm:mt-0 sm:col-span-2">
            <%= f.text_field :tel %>
          </div>
        </div>

        <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
          <%= f.submit '資訊更新', class:'text-white text-sm p-2 rounded bg-gray-500 hover:bg-gray-900' %>
        </div>

      <% end %>
  </div>
</div>

app/views/shops/index.html.erb
<div class='flex flex-grow items-center flex-col space-y-4 pb-10 pt-28'>
  <%# 商品顯示 %>
  <div class='bg-gray-50 w-11/12 rounded-sm overflow-hidden border-1 shadow  overflow-y-auto ',style='height:500px'>
      <table class='w-full text-center border-collapse'>
      <thead class='bg-gray-100 text-gray-500'>
        <tr>
            <td class='p-2'>商品圖片</td>
            <td>商品名稱</td>
            <td>商品描述</td>
            <td>商品數量</td>
            <td>商品價格</td>
            <td>上架時間</td>
            <td>下架時間</td>
            <td>上架狀態</td>
            <td colspan='2'>商品設定</td>
        <tr>
      </thead>

      <tbody>
        <% @products.each do |product|%>
          <tr class='border-b-2 border-fuchsia-600 h-24'>
              <td class='flex justify-center items-center w-full h-24 px-4'>
                <% if product.image_url.present? %>
                  <div class='w-20 h-20'><%= image_tag product.image_url, style:'width:100%;height:100%;object-fit:cover' %></div>
                <% else %>
                  <div class="picture dark"><%= image_tag 'bag.png' %></div>
                <% end %>
              </td>
              <td class='w-1/12'><%= product.name %></td>
              <td class='w-2/12'><%= product.content %></td>
              <td class='w-1/12'><%= product.quantity %></td>
              <td class='w-1/12'><%= product.price %></td>
              <td class='w-2/12'><%= product.schedule_start ? product.schedule_start.strftime("%Y-%m-%d %H:%M") : ""%></td>
              <td class='w-2/12'><%= product.schedule_end ? product.schedule_end.strftime("%Y-%m-%d %H:%M") : "" %></td>
              <td class='w-1/12'> <%= product.status==0 ? "上架" : "下架"%></td>
              <td class='w-1/12'><%= link_to "編輯", edit_product_path(product), class:'text-white text-sm p-2 rounded bg-gray-500 hover:bg-gray-900' %>
              </td>
              <td class='w-1/12'><%= link_to "刪除", product_path(product), method: "delete", data: {confirm: "確定刪除嗎？"}, class:'text-red-500 text-sm p-2 rounded bg-white border border-red-500 hover:text-white hover:bg-red-500' %></td>
          </tr>
        <% end %>
      </tbody>
      </table>
  </div>
</div>

app/views/shops/new.html.erb
<div class="overflow-hidden sm:rounded-lg my-20 m-auto mt-40">
  <div class="border-t border-gray-200">
      <%= form_for @shop do |f| %>

        <div class="bg-white py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <div class="block text-sm font-medium text-gray-700">
            <%= f.label :name, '賣場名稱' %>
          </div>
          <div class="mt-1 text-sm text-gray-900 border-b border-text-200 sm:mt-0 sm:col-span-2">
            <%= f.text_field :name %>
          </div>
        </div>

        <div class="bg-white py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
          <div class="block text-sm font-medium text-gray-700">
            <%= f.label :tel, '聯絡電話' %>
          </div>
          <div class="mt-1 text-sm text-gray-900 border-b border-text-200  sm:mt-0 sm:col-span-2">
            <%= f.text_field :tel %>
          </div>
        </div>

        <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
          <%= f.submit '創立店家', class:'text-white text-sm p-2 rounded bg-gray-500 hover:bg-gray-900' %>
        </div>

      <% end %>
  </div>
</div>