config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  root 'pages#home'
  get :search, to: 'products#search'
  get :my_favorite, to: 'products#my_favorite'

  resources :orders do
    collection do
      post :return
    end
  end

  resources :shops do
    resources :products, shallow: true do
      member do
        post :favorite
      end
    end
  end

  resources :order_list, shallow: true

  resources :users do
    collection do
      post :add_coupon
      get :change_coupon_status
    end
  end

  resources :coupons do
    collection do
      get :list
    end
  end

  resources :rooms do
    resources :messages , shallow: true
  end

  resource :carts, only:[:show, :destroy] do
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    get :checkout
    post :return
    get 'get_coupon_info/:id', action: 'get_coupon_info', as: 'get_coupon_info'
    get 'cal_totalprice', action: 'cal_totalprice', as: 'cal_totalprice'
    delete :empty
    delete 'destroy/:id', action: 'destroy', as: 'destroy'
    put 'update_item/:id', action: 'update_item', as: 'update_item'
  end
end

app/controllers/order_list_controller.rb
class OrderListController < ApplicationController
  layout 'store'

  def index
    @orders = current_user.shop.orders
  end

  def show
    @order = current_user.shop.orders.find(params[:id])
    @products = Product.joins(:sub_orders).where(sub_orders: {order: @order})
  end
end

app/views/order_list/index.html.erb
<div class='flex flex-grow items-center flex-col space-y-4 pb-10 pt-36'>
  <div class='h-5/6 bg-gray-50 w-10/12 rounded-sm overflow-hidden border-1 shadow'>

    <table class="w-full text-center border-collapse">
      <thead class="bg-gray-100 text-gray-500">
        <tr>
          <th class='p-2'>訂單編號</th>
          <th></th>
          <th>購買日期</th>
          <th>訂單金額</th>
          <th>訂單狀態</th>
          <th>聯絡買家</th>
        <tr>
      </thead>

      <tbody>
        <% @orders.each do |order| %>
          <tr class='border-b-2 border-fuchsia-600 h-20'>
            <td class='w-1/6'><%= order.number %></td>
            <td class='w-1/6'><%= link_to '訂單詳情', order_list_path(order), class:'text-white text-sm p-2 rounded bg-gray-500 hover:bg-gray-900' %></td>
            <td class='w-1/6'><%= order.created_at.strftime('%Y-%m-%d') %></td>
            <td class='w-1/6'><%= 'NT '+ order.sum.to_s %></td>
            <td class='w-1/6'><%= t("order_status.#{order.status}") %></td>
            <td class='w-1/6'><%= link_to '聊聊', root_path, class:'text-white text-sm p-2 rounded bg-red-500 hover:bg-red-900' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/order_list/show.html.erb
<div class='flex flex-grow items-center flex-col space-y-4 pb-10 pt-36'>
  <div class='h-5/6 bg-gray-50 w-10/12 rounded-sm overflow-auto border-1 shadow'>

    <table class="w-full text-center border-collapse">
      <thead class="bg-gray-100 text-gray-500">
        <tr>
          <th>購買商品</th>
          <th></th>
          <th>購買數量</th>
          <th>單價</th>
          <th>收件者</th>
          <th>聯絡電話</th>
          <th>寄送地址</th>
          <th></th>
        <tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
        <tr class='border-b-2 border-fuchsia-600 h-20'>
          <td class='w-1/12'><%= image_tag product.image.to_s %></td>
          <td class='w-2/12'><%= product.name %></td>
          <td class='w-2/12'><%= product.quantity %></td>
          <td class='w-1/12'><%= product.price %></td>
          <td class='w-1/12'><%= @order.receiver %></td>
          <td class='w-1/12'><%= @order.tel %></td>
          <td class='w-3/12'><%= @order.address %></td>
          <td class='w-1/12'><%= link_to '回上頁', order_list_index_path, class:'text-white text-sm p-2 rounded bg-gray-500 hover:bg-gray-900' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>