config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  root 'pages#home'
  get :search, to: 'products#search'
  get :my_favorite, to: 'products#my_favorite'

  resources :orders do
    collection do
      post :return
    end
  end

  resources :shops do
    resources :products, shallow: true do
      member do
        post :favorite
      end
    end
  end

  resources :order_list, shallow: true

  resources :users do
    collection do
      post :add_coupon
      get :change_coupon_status
    end
  end

  resources :coupons do
    collection do
      get :list
    end
  end

  resources :rooms do
    resources :messages , shallow: true
  end

  resource :carts, only:[:show, :destroy] do
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    get :checkout
    post :return
    get 'get_coupon_info/:id', action: 'get_coupon_info', as: 'get_coupon_info'
    get 'cal_totalprice', action: 'cal_totalprice', as: 'cal_totalprice'
    delete :empty
    delete 'destroy/:id', action: 'destroy', as: 'destroy'
    put 'update_item/:id', action: 'update_item', as: 'update_item'
  end
end

app/views/shared/_card.html.erb
<section class="cards">
    <div class="content max-auto">
      <% @products.each do |product|%>
        <div class='onecard'>
          <div class="cardstyle">
            <%= link_to product_path(product) do %>
            <div>
              <% if product.image_url.present? %>
                <div class="picture"><%= image_tag product.image_url %></div>
              <% else %>
                <div class="picture dark"><%= image_tag 'bag.png' %></div>
              <% end %>
            </div>
            <div class='item'>
              <%= product.name %>
              <div>
                <div>$<%= product.price %></div>
              </div>
            </div>
          </div>
        <% end %>
          <%= form_tag({ controller: "products", action: "search" }, method: "get", class: "z-1") %>
          <%= submit_tag '找相似',class:'searchsame opacity-0' %>
          <%= text_field_tag 'search', product.name, class:'opacity-0' %>
        </div>
      <% end %>
    </div>
</section>

app/views/shared/_membernav.html.erb
<nav class='flex w-full items-center bg-gray-50 px-2 lg:px-10 text-black shadow flex-wrap justify-between fixed top-0'>
  <div class="flex items-center">
    <%= link_to root_path do %>
      <%= image_tag "logowithoutword.png" , class:'w-20' %>
    <% end %>
    <h2 class='text-2x1'>會員中心</h2>
  </div>
  <div>
    <div class='inline-flex py-5 space-x-4 w-full'>
      <!-- <div><%= link_to '首頁', root_path %></div> -->
        <% if user_signed_in? %>
        <div class='hover:bg-gray-900'><%= link_to '登出' ,
          destroy_user_session_path ,
          method: 'delete' %>
          </div>
      <% else %>
        <div class='hover:text-pink-300'><%= link_to '註冊', new_user_registration_path %></div>
        <div class='hover:text-pink-300'><%= link_to '登入',  new_user_session_path  %></div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_membersidebar.html.erb
<div class="h-screen bg-gray-50 pt-16 w-60 shadow text-lg text-gray-600">
  <div class="flex pl-12 flex-col pt-20 space-y-2">

    <div class="pl-7">
      <%= link_to '我的帳戶', edit_user_registration_path if current_user %>
    </div>

    <div class="pl-7">
      <%= link_to '購買清單', orders_path if current_user %>
    </div>

    <div class="pl-7">
      <%= link_to '收藏商品', my_favorite_path if current_user %>
    </div>

    <div class='pl-7'>
      <%= link_to '回首頁', root_path if current_user.shop.present?%>
    </div>

  </div>
</div>

app/views/shared/_nav.html.erb
<nav class='primarynav'>
  <div class='px-1'>
    <button class="text-gray-900 inline-flex mr-2 p-2 hover:bg-gray-900 rounded lg:hidden ml-auto hover:text-white focus:outline-none nav-toggler">
      <i class="fas fa-bars"></i>
    </button>
  </div>

  <div class='logo'>
    <%= link_to root_path do %>
      <%= image_tag "logoblack.png" %>
    <% end %>
  </div>

  <div class='searchbar w-1/5 md:1/2 sm:3/5'>
    <%= form_tag search_path, method: :get do %>
      <div class="search">
        <span class="btn">
          <%= button_tag(type: "submit", class:"icon") do %>
            <i class="fas fa-search"></i>
          <% end %>
        </span>
        <% if ['電玩','書本','衣服','服務,票卷','寵物','家電影音','居家生活','模型','美食','其他'].include?(params[:search]) %>
          <%= text_field_tag :search,'',placeholder: "搜尋商品", class:'inputsearch' %>
        <% else %>
          <%= text_field_tag :search, params[:search], placeholder: "搜尋商品", class:'inputsearch' %>
        <% end %>
      </div>
    <% end %>
  </div>
    <%= link_to carts_path do %>
      <% if current_user %>   
        <div class='text-gray-900 flex items-center mr-1' data-controller="navcart" data-action="plusbtn@window->navcart#update changequantity@window->navcart#update minusbtn@window->navcart#update usecoupon@window->navcart#update unusecoupon@window->navcart#update"><%= image_tag 'bag.png' ,class:'w-8'%> <span class="cartCount" data-navcart-target="cartcount"><%= current_cart.items.count %></span> / <span class="cartTotalPrice" data-navcart-target="carttotalprice"><%= current_cart.total_price %></span></div>
      <% end %>
    <% end %>
    <div class='hidden top-navbar w-full md:inline-flex md:w-auto text-gray-900 navigation bg-white pl-2 md:space-x-2 items-center'>
      <% if user_signed_in? %>
          <div class='py-4'><%= link_to '登出',  destroy_user_session_path , method: 'delete' %></div>
        <% if current_user.shop.blank? %>
          <div class='py-4'><%= link_to '我要開店', new_shop_path %></div>
        <% else %>
          <div class='py-4'><%= link_to '賣家中心', shops_path %></div>
        <% end %>
          <%= link_to user_path(current_user) do %>
            <% if current_user.image.url.blank? %>
              <i class="fas fa-user-circle text-3xl"></i>
            <% else %>
              <%= image_tag current_user.image.url, class:"m-auto rounded-full h-10 w-10" if current_user.image.url.present? %>
            <% end %>
          <% end %>
      <% else %>
        <div class='py-4 pl-2'><%= link_to '註冊', new_user_registration_path %></div>
        <div class='py-4 pl-2'><%= link_to '登入',  new_user_session_path  %></div>
      <% end %>
    </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="h-screen bg-gray-50 pt-16 w-60 shadow text-lg text-gray-600">
  <div class="flex pl-12 flex-col pt-20 space-y-2">

    <div>
      <i class="fas fa-store"></i>
      <%= link_to '商品列表', shops_path if current_user.shop.present? %>
    </div>

    <div class="pl-7">
      <%= link_to '新增商品', new_shop_product_path(current_user.shop) if current_user.shop.present? %>
    </div>

    <div>
      <i class="fas fa-ticket-alt"></i>
      <%= link_to '檢視優惠券', list_coupons_path if current_user.shop.present? %>
    </div>

    <div class="pl-7">
      <%= link_to '新增優惠券', new_coupon_path if current_user.shop.present? %>
    </div>

    <div class='pl-7'>
      <%= link_to '訂單列表', order_list_index_path if current_user.shop.present?%>
    </div>

    <div class='pl-7'>
      <%= link_to '賣場設定', edit_shop_path(current_user.shop) if current_user.shop.present?%>
    </div>

    <div class='pl-7'>
      <%= link_to '回首頁', root_path if current_user.shop.present?%>
    </div>

  </div>
</div>

app/views/shared/_storenav.html.erb
<nav class='flex w-full items-center bg-gray-50 px-2 lg:px-10 text-black shadow flex-wrap justify-between fixed top-0'>
  <div class="flex items-center">
    <%= link_to root_path do %>
      <%= image_tag "logowithoutword.png" , class:'w-20' %>
    <% end %>
    <h2 class='text-2x1'>賣家中心</h2>
  </div>
  <div>
    <div class='inline-flex py-5 space-x-4 w-full'>
      <!-- <div><%= link_to '首頁', root_path %></div> -->
        <% if user_signed_in? %>
        <div class='hover:bg-gray-900'><%= link_to '登出' ,
          destroy_user_session_path ,
          method: 'delete' %>
          </div>
      <% else %>
        <div class='hover:text-pink-300'><%= link_to '註冊', new_user_registration_path %></div>
        <div class='hover:text-pink-300'><%= link_to '登入',  new_user_session_path  %></div>
      <% end %>
    </div>
  </div>
</nav>