config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  root 'pages#home'
  get :search, to: 'products#search'
  get :my_favorite, to: 'products#my_favorite'

  resources :orders do
    collection do
      post :return
    end
  end

  resources :shops do
    resources :products, shallow: true do
      member do
        post :favorite
      end
    end
  end

  resources :order_list, shallow: true

  resources :users do
    collection do
      post :add_coupon
      get :change_coupon_status
    end
  end

  resources :coupons do
    collection do
      get :list
    end
  end

  resources :rooms do
    resources :messages , shallow: true
  end

  resource :carts, only:[:show, :destroy] do
    post 'add_item/:id', action: 'add_item', as: 'add_item'
    get :checkout
    post :return
    get 'get_coupon_info/:id', action: 'get_coupon_info', as: 'get_coupon_info'
    get 'cal_totalprice', action: 'cal_totalprice', as: 'cal_totalprice'
    delete :empty
    delete 'destroy/:id', action: 'destroy', as: 'destroy'
    put 'update_item/:id', action: 'update_item', as: 'update_item'
  end
end

app/models/cart.rb
class Cart
  attr_reader :items, :coupons, :total, :subtotals
  def initialize(items = [], coupons = [], total = 0, subtotals = [])
    @items = items
    @coupons = coupons
    @total = total
    @subtotals = subtotals
  end

  def add_item(product_id, quantity = 1)
    found_item = @items.find { |item| item.product.id == product_id }
    if found_item
      found_item.increament(quantity)
    else
      @items << CartItem.new(product_id, quantity)
    end
  end

  def empty?
    @items.empty?
  end

  def product_ids
    @items.map(&:product_id)
  end

  def total_price
    if not @subtotals.empty?
      @total = @subtotals.reduce(0) {|sum, item| sum + item[0]}
    else
      @total = 0
    end
    total = @total
    total
  end

  def cal_discount(shop_id,current_user, sum)
    coupon_id = Shop.find(shop_id).coupons.pluck(:id) & current_user.user_coupons.pluck(:coupon_id)
    if not coupon_id.empty?
      coupon = Coupon.find(coupon_id[0])
      discount_rule = coupon.discount_rule
      discount_amount = coupon.discount_amount.to_i
      min_consumption = coupon.min_consumption.to_i
      if min_consumption < sum
        if discount_rule == '折扣'
          discount = (sum * discount_amount * 0.01).floor()
        elsif discount_rule == '金額'
          discount = discount_amount
        end
      else
        discount = 0
      end
    else
      discount = 0
    end
    if @subtotals.filter { |shoptotal, shopid| shopid == shop_id }.empty?
      @subtotals << [sum-discount, shop_id]
    else
      @subtotals = @subtotals.map { |origin_shoptotal, shopid| shopid == shop_id ? [sum-discount, shop_id] : [origin_shoptotal, shopid] }
    end
    discount
  end

  def use_coupon(usercoupon_id, shop_id)
    if @coupons.filter { |usercoupon, shop| usercoupon == usercoupon_id}.empty?
      @coupons << [usercoupon_id, shop_id]
    end
  end

  def unuse_coupon(usercoupon_id, shop_id)
    use_coupon = !(@coupons.filter { |usercoupon, shop| usercoupon == usercoupon_id}.empty?)
    if use_coupon
      @coupons = @coupons.filter { |usercouponid, shopid| usercouponid != usercoupon_id }
    end
  end

  def destroy(product)
    @items = @items.filter { |item| item.product_id != product}
    shop_id = Product.find(product).shop_id
    shop_items = @items.filter{ |item| item.shop_id == shop_id }
    
    if shop_items.empty?
      @subtotals = @subtotals.filter {|origin_shoptotal, shopid| shopid != shop_id}
    else
      shoptotal = shop_items.reduce(0) { |shoptotal, item| shoptotal + item.total_price }
      @subtotals = @subtotals.map { |origin_shoptotal, shopid| shopid == shop_id ? [shoptotal, shop_id] : [origin_shoptotal, shopid] }
    end
    
  end

  def shop_totalprice(shop_id)
    shop_items = @items.filter { |item| item.shop_id == shop_id }
    shoptotal = shop_items.reduce(0) { |shoptotal, item| shoptotal + item.total_price }

    user_use_shop_coupon = !(@coupons.filter {|usercouponid, shopid| shopid == shop_id}.empty?)    
    if user_use_shop_coupon
      usercouponid, shopid = @coupons.filter {|usercouponid, shopid| shopid == shop_id}[0]
      couponid = UserCoupon.find_by(id: usercouponid).coupon_id
      coupon = Coupon.find_by(id: couponid)
      discount_amount = coupon.discount_amount
      discount_rule = coupon.discount_rule
      if discount_rule == '金額'
        shoptotal -= discount_amount
      elsif discount_rule == '折扣'
        shoptotal = (shoptotal * (1 - 0.01 * discount_amount.to_i)).floor()
      end 
    end

    if @subtotals.filter { |shoptotal, shopid| shopid == shop_id }.empty?
      @subtotals << [shoptotal, shop_id]
    else
      @subtotals = @subtotals.map { |origin_shoptotal, shopid| shopid == shop_id ? [shoptotal, shop_id] : [origin_shoptotal, shopid] }
    end
  end

  def cal_cart_total 
    if not @subtotals.empty?
      @total = @subtotals.reduce(0) {|sum, item| sum + item[0]}
    end      
  end

  def serialize
    items = @items.map do |item|
      {
        "product_id" => item.product.id,
        "quantity" => item.quantity
      }
    end
    sub_totals = @subtotals.map do |subtotal|
      {
        "shoptotal" => subtotal[0],
        "shop_id" => subtotal[1]
      }
    end
    coupons = @coupons.map do |coupon|
      {
        "usercoupon" => coupon[0],
        "shop_id" => coupon[1]
      }
    end
    total = {"total" => @total}

    { 
      "items" => items,
      "subtotals" => sub_totals,
      "coupons" => coupons,
      "total" => total
    }
  end

  def items_name
    items.map { |item| "#{item.product.name} x #{item.quantity}" }.join('#')
  end

  def self.from_hash(hash)
    if hash && hash["items"] && hash["subtotals"] && hash["coupons"] && hash["total"]
      items = hash["items"].map do |item|
        CartItem.new(item["product_id"], item["quantity"])
      end
      sub_totals = hash["subtotals"].map do |subtotal|
        [subtotal["shoptotal"], subtotal["shop_id"]]
      end
      _coupons = hash["coupons"].map do |coupon|
        [coupon["usercoupon"], coupon["shop_id"]]
      end
      _total = hash["total"]["total"].to_i
      Cart.new(items,coupons=_coupons, total=_total, subtotals=sub_totals)
    else
      Cart.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # before_action :authenticate_user! ,only:[:add_item]
  skip_before_action :verify_authenticity_token, only: :return

  def add_item
    if current_user
      product = Product.find(params[:id])
      quantity = JSON.parse(params.keys.filter{|i| i[/.amount/]}.first)["amount"].to_i
      current_cart.add_item(product.id, quantity)
      current_cart.shop_totalprice(product.shop_id)
      current_cart.cal_cart_total
      session[:cartgo] = current_cart.serialize
      redirect_to root_path, notice: '已加入購物車'
    else
      redirect_to user_session_path
    end
  end

  def update_item
    if current_user
      product = Product.find(params[:id])
      quantity = JSON.parse(params.keys.filter{|i| i[/.amount/]}.first)["amount"].to_i
      current_cart.add_item(product.id, quantity)
      current_cart.shop_totalprice(product.shop_id)
      current_cart.cal_cart_total
      shoptotal = current_cart.subtotals.filter {|total, shopid| shopid == product.shop_id}[0][0]
      session[:cartgo] = current_cart.serialize
      render json:{ status: 'ok',
                    count: current_cart.items.count,
                    total_price: current_cart.total_price,
                    change: quantity,
                    shoptotal: shoptotal,
                    shopID: product.shop_id
                  }
    else
      redirect_to user_session_path
    end
  end

  def show
    if not current_user
      redirect_to user_session_path
    end
  end

  def empty
    session[:cartgo] = nil
    redirect_to root_path, notice: '購物車已清除'
  end

  def destroy
    current_cart.destroy(params[:id].to_i)
    current_cart.cal_cart_total
    session[:cartgo] = current_cart.serialize
    redirect_to carts_path
  end

  def get_coupon_info
    coupon = Coupon.find(params[:id])
    user_coupons = current_user.user_coupons.where(coupon_id: params[:id])
    own = !(user_coupons.empty?)

    if own
      status = user_coupons.pluck(:coupon_status)
      id = user_coupons.pluck(:id)

      render json: {
        discount_rule: coupon[:discount_rule],
        discount_start: coupon_TimeWithZone_convert(coupon[:discount_start]),
        discount_end: coupon_TimeWithZone_convert(coupon[:discount_end]),
        min_consumption: coupon[:min_consumption],
        discount_amount: coupon[:discount_amount],
        amount: coupon[:amount],
        counter_catch: coupon[:counter_catch],
        usercoupon_id: id,
        occupy: own,
        status: status
      }
    else
      render json: {
        discount_rule: coupon[:discount_rule],
        discount_start: coupon_TimeWithZone_convert(coupon[:discount_start]),
        discount_end: coupon_TimeWithZone_convert(coupon[:discount_end]),
        min_consumption: coupon[:min_consumption],
        discount_amount: coupon[:discount_amount],
        amount: coupon[:amount],
        counter_catch: coupon[:counter_catch],
        occupy: own
      }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def current_cart
    p  "helper#{session[:cartgo]}"
    @_cartgo ||= Cart.from_hash(session[:cartgo])
  end
end

app/views/carts/_cart.html.erb
<style>
  .input_amount[type="number"]::-webkit-inner-spin-button,
  .input_amount[type="number"]::-webkit-outer-spin-button {
  -webkit-appearance: none;
  margin: 0;
}


.coupon {
    border: 1px solid ;
    padding: 5px;
    display: flex;
  }

.occupy {
  background-color: grey;
  pointer-events: none
}

</style>
<table>
  <thead>
    <tr>
      <td>商品圖片</td>
      <td>商品名稱</td>
      <td>商品描述</td>
      <td>商店名稱</td>
      <td>數量</td>
      <td>單價</td>
      <td>小計</td>
      <td>處理</td>
    </tr>
  </thead>
  <% items = (cart.items.sort_by {|item| Product.find_by(id: item.product_id).shop.id })%>
  <% items.each do |item| %>
    <tbody data-controller="updatecart" data-updatecart-id="<%= item.product.id %>" data-updatecart-number-value="<%= item.quantity %>" data-updatecart-totaprice-value="0">
      <tr>
        <td><%= link_to product_path(item.product) do %><%= image_tag item.product.image_url if item.product.image_url.present? %><% end %></td>
        <td><%= item.product.name %></td>
        <td><%= item.product.content %></td>
        <td><%= item.product.shop.name %></td>
        <td><%= item.quantity %></td>
        <td><%= item.product.price %></td>
        <td><%= item.total_price %></td>
        <td>
          <div class="amount">
            <button class="minus" data-action="click->updatecart#minusbtn">-</button>
            <input type="number" class="input_amount" data-updatecart-target="amount" data-action="input->updatecart#changequantity">
            <button class="plus" data-action="click->updatecart#plusbtn">+</button>
          </div>
        </td>
        <td data-updatecart-target="price"><%= item.product.price %></td>
        <td data-updatecart-target="totalprice" class="item_total_price" data-shopid="<%= item.product.shop_id %>"></td>
        <td>
          <a href='#' data-action="click->updatecart#destroy">取消</a>
        </td>
      </tr>
      <tr>
        <td colspan="8">
          <% Coupon.where(shop_id: item.product.shop_id).pluck(:title, :id).each do |title, coupon_id| %>
              <a data-action="click->updatecart#getcoupon" data-couponid="<%= coupon_id %>" class=" <%= UserCoupon.where(coupon_id: coupon_id, user_id: current_user) ? 'occupy' : '' %>">
                <%= title %>
              </a>
              <span data-couponid="<%= coupon_id %>" data-itemid="<%= item.product.id %>" data-action="click->updatecart#usecoupon">使用</span>
          <% end %>
        </td>
      </tr>
    </div>
  <% end %>
  <tfoot>
    <tr>
      <td colspan="3">總價</td>
      <td class="cart_total"><%= cart.total_price %></td>
    </tr>
  </tfoot>
</table>

app/views/carts/_checkoutcart.html.erb
<div>
<% items = (cart.items.sort_by {|item| item.product.shop_id})%>
<% temp = items.group_by { |item| item.product.shop_id.itself} %>
    
  <% temp.values.each do |items|%>
      <div data-controller="shoptotal" data-shoptotal-id="<%= items[0].shop_id %>" class="flex flex-col">
      <!-- 店家名稱 -->
        <div class="py-2 border-b border-gray-800 text-gray-800"><i class="fas fa-store mr-2"></i><%= items[0].product.shop.name %></div>
        <% items.each do |item| %>
        <div class="flex py-2 border-b border-gray-900" data-controller="updatecart" data-updatecart-id
        ="<%= item.product.id %>" data-updatecart-number-value="<%= item.quantity %>" data-updatecart-totalprice-value="0">
          <div>
            <%= link_to product_path(item.product) do %>
              <% if item.product.image_url.present? %>
              <div class='w-24 h-24'><%= image_tag item.product.image_url ,style:'width:100%;height:100%;object-fit:cover' %></div>
              <% else %>
              <div class="picture  w-24 h-24 dark"><%= image_tag 'bag.png' %></div>
              <% end %>
            <% end %>
          </div>
          <div class="flex flex-col justify-between w-full pl-4 py-2">
          <!-- 商品名稱 -->
            <div class="flex justify-between">
              <div class='text-xl'>
                <%= item.product.name %>
              </div>
              <div>
                <a href="#" data-action="click->updatecart#destroy">&#x292C;</a>
              </div>
            </div>
            <div class="flex flex-row items-end justify-between h-full pr-5">
              <!-- 數量 -->
              <div class="amount flex border border-gray-300 rounded-sm px-2 h-8 w-24">
                <button class="minu border-r border-gray-300 pr-2 focus:outline-none" data-action="click->updatecart#minusbtn">-</button>
                <input type="number" class="input_amount w-12 text-center" data-updatecart-target="amount" data-action="input->updatecart#changequantity">
                <button class="plus border-l border-gray-300 pl-2 focus:outline-none" data-action="click->updatecart#plusbtn">+</button>  
              </div>
              <!-- 價錢 -->
              <div data-updatecart-target="price" class="self-start">
                $<%= item.product.price %>
              </div>
            </div>
            <!-- 商品小計hidden -->
            <div class="item_total_price hidden" data-updatecart-target="totalprice" data-shopid="<%= item.product.shop_id %>">
              <%= item.total_price %>
            </div>
          </div>
      </div>
      <% end %>
      </div>

      <div>
      <div class='flex text-lg'>
        總金額 : 
        <span data-shoptotal-target="shoptotal" data-shopid="<%= items.first.product.shop_id %>">
        <%= current_cart.subtotals.filter {|subtotal, shopid| shopid == items.first.shop_id}[0][0] %> 
        <% end %>
        </span>
      </div>
      </div>
    </div>

  
  

app/views/carts/_showcart.html.erb
<div class="wrap flex justify-center w-screen overflow-auto">
  <div class="w-9/12 flex flex-wrap h-full">
    <div class="pb-2 border-b border-gray-900" style="flex:100%">&#x2190;<%= link_to '繼續購買', root_path ,class:'pl-2' %></div>
    <% items = (cart.items.sort_by {|item| item.product.shop_id})%>
    <% temp = items.group_by { |item| item.product.shop_id.itself} %>
    <div class="md:w-3/5 w-full">
    <% temp.values.each do |items|%>
        <div data-controller="shoptotal" data-shoptotal-id="<%= items[0].shop_id %>" class="flex flex-col w-full">
          <!-- 店家名稱 -->
          <div class="py-2 border-b border-gray-800 text-gray-800"><i class="fas fa-store mr-2"></i><%= items[0].product.shop.name %></div>
          <% items.each do |item| %>
            <div class="flex py-2 border-b border-gray-900 w-full" data-controller="updatecart" data-updatecart-id="<%= item.product.id %>" data-updatecart-number-value="<%= item.quantity %>" data-updatecart-totalprice-value="0">
              <div>
                <%= link_to product_path(item.product) do %>
                  <% if item.product.image_url.present? %>
                    <div class='w-24 h-24'><%= image_tag item.product.image_url ,style:'width:100%;height:100%;object-fit:cover' %></div>
                  <% else %>
                    <div class="picture  w-24 h-24 dark"><%= image_tag 'bag.png' %></div>
                  <% end %>
                <% end %>
              </div>
              <div class="flex flex-col justify-between w-full pl-4 py-2">
                <!-- 商品名稱 -->
                <div class="flex justify-between">
                  <div class='text-xl'>
                    <%= item.product.name %>
                  </div>
                  <div>
                    <a href="#" data-action="click->updatecart#destroy">&#x292C;</a>
                  </div>
                </div>
                <div class="flex flex-row items-end justify-between h-full pr-5">
                  <!-- 數量 -->
                  <div class="amount flex border border-gray-300 rounded-sm px-2 h-8 w-24">
                    <button class="minus border-r border-gray-300 pr-2 focus:outline-none" data-action="click->updatecart#minusbtn">-</button>
                    <input type="number" class="input_amount w-12 text-center" data-updatecart-target="amount" data-action="input->updatecart#changequantity">
                    <button class="plus border-l border-gray-300 pl-2 focus:outline-none" data-action="click->updatecart#plusbtn">+</button>  
                  </div>
                  <!-- 價錢 -->
                  <div data-updatecart-target="price" class="self-start">
                    $<%= item.product.price %>
                  </div>
                </div>
                <!-- 商品小計hidden -->
                <div class="item_total_price hidden" data-updatecart-target="totalprice" data-shopid="<%= item.product.shop_id %>">
                  <%= item.total_price %>
                </div>
              </div>
            </div>
          <% end %>
          <!-- coupon -->
          <div class=" space-x-4">
            <div>請點選優惠券領取</div>
            <% Coupon.where(shop_id: items[0].product.shop_id).pluck(:title, :id).each do |title, coupon_id| %>
              <div class="flex py-2 items-center space-x-2">
                <div class="coupon <%= user_own_coupon?(coupon_id) ? 'occupy' : '' %>">
                  <div class='<%= user_own_coupon?(coupon_id) ? 'occupy' : '' %> cursor-pointer' data-action="click->shoptotal#getcoupon" data-couponid="<%= coupon_id %>">
                    <% information = Coupon.where(id: coupon_id).pluck(:min_consumption, :discount_rule, :discount_amount) %>
                    <% min= information[0][0] %>
                    <% rule= information[0][1] %>
                    <% discount= information[0][2] %>
                    <% if rule == '金額'%>
                      <%= "滿#{min}折#{discount}元" %>
                    <% elsif rule == '折扣' %>
                      <%= "滿#{min}折#{discount}%" %>
                    <% end %>
                  </div>
                  <div class='cursor-pointer <%= user_own_coupon?(coupon_id) ? 'occupy' : '' %> cursor-pointer' data-action="click->shoptotal#getcoupon" data-couponid="<%= coupon_id %>">
                    
                  </div>
                  <% if user_use_coupon?(coupon_id) %>
                  <div data-couponid="<%= coupon_id %>" data-shopid="<%= items[0].product.shop_id %>" data-action="click->shoptotal#usecoupon" class="cursor-pointer usage">
                      使用中
                  </div>
                <% else %>
                  <div data-couponid="<%= coupon_id %>" data-shopid="<%= items[0].product.shop_id %>" data-action="click->shoptotal#usecoupon" class="cursor-pointer usage">
                    未使用
                  </div>
                <% end %>
                <a data-action="click->shoptotal#unusecoupon" class="cursor-pointer">&#x292C;</a>

                </div>
              </div>
            <% end %>
          </div>
          <div class='flex text-lg'>
            總金額 : 
            <span data-shoptotal-target="shoptotal" data-shopid="<%= items.first.product.shop_id %>">
            <%= current_cart.subtotals.filter {|subtotal, shopid| shopid == items.first.shop_id}[0][0] %> 
            </span>
          </div>
        </div>      
      <!-- <div class="mt-2">小計:</div> -->
    <% end %>
  </div>
    <!-- 右邊 -->
    <div class="md:flex-1 w-full flex-col space-y-4 ml-5 flex h-32 relative top-0">
    <div class='flex p-4 bg-gray-100 mt-10 text-lg justify-end'>
      <% if current_cart.present?%>
      <div class='flex w-28 justify-between'>
        <div>總價:</div>
        <span class="cart_total"><%= cart.cal_cart_total %></span>
      </div>
      <% end %>
    </div>
    <!-- <%= link_to '清空購物車', empty_carts_path, method: "delete" %> -->
    <% if not current_cart.empty? %>
    <button class="px-8 py-2 bg-red-500 text-white w-36 rounded-sm absolute right-0 -bottom-4 focus:outline-none hover:bg-red-600">
    <%= link_to '結帳', new_order_path %></button>
    <% end %>
    </div>
  </div>
</div>

app/views/carts/checkout.html.erb
<h1>結帳</h1>

<%= render 'checkoutcart', cart: current_cart %>

<form id="cart-form" action='https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5' method="post">
  <%= hidden_field_tag :MerchantID, @hash['MerchantID'] %>
  <%= hidden_field_tag :MerchantTradeNo, @hash['MerchantTradeNo'] %>
  <%= hidden_field_tag :MerchantTradeDate, @hash['MerchantTradeDate'] %>
  <%= hidden_field_tag :PaymentType, @hash['PaymentType'] %>
  <%= hidden_field_tag :TotalAmount, @hash['TotalAmount'] %>
  <%= hidden_field_tag :TradeDesc, @hash['TradeDesc'] %>
  <%= hidden_field_tag :ItemName, @hash['ItemName'] %>
  <%= hidden_field_tag :ReturnURL, @hash['ReturnURL'] %>
  <%= hidden_field_tag :ClientBackURL, @hash['ClientBackURL'] %>
  <%= hidden_field_tag :ChoosePayment, @hash['ChoosePayment'] %>
  <%= hidden_field_tag :EncryptType, @hash['EncryptType'] %>
  <%= hidden_field_tag :CheckMacValue, @shavalue %>
</form>

<button id="btn">付款</button>
<script>
(function() {
  document.getElementById('btn').addEventListener('click', function() {
    document.getElementById('cart-form').submit();
  })
})();
</script>

app/views/carts/show.html.erb
<h1>購物車</h1>
<%= render 'showcart', cart: current_cart %>